### ISSUE TITLE
Drush pm and make commands should properly handle project status url

### ISSUE THREAD

**Issue by iamEAP** [drush-ops/drush#19]
Copied from https://drupal.org/node/2043513

**Comment by JorisVanEijden** [comment]
:+1:

**Comment by jonhattan** [comment]
Please elaborate. `pm-` commands were recently fixed in #1460.

`make` supports status url (via 'location' param) but we don't have an alternative update xml to test and prevent regressions. (Ref: https://www.drupal.org/node/1520802)

**Comment by ergonlogic** [comment]
At a minimum, we'd need confirmation that the documented issues remain. Patches in the originating d.o issue are for Drush 6, and so would have to be re-rolled (or converted into a pull request).

I'm going to close this issue, pending someone setting up an alternative status url we can test against.
