### ISSUE TITLE
Notice: "Undefined index: name annotationcommand_adapter.inc:500" using drush make

### ISSUE THREAD

**Issue by gitressa** [drush-ops/drush#2407]
I saw these Notices started popping up a few days ago, probably nothing serious ...

<pre>$ drush make website.make.yml drupal --verbose;

Undefined index: name annotationcommand_adapter.inc:500                                                                                   [notice]
Loading release_info engine.                                                                                                              [notice]
Undefined index: name annotationcommand_adapter.inc:500                                                                                   [notice]
Undefined index: name annotationcommand_adapter.inc:500                                                                                   [notice]
Undefined variable: annotationData annotationcommand_adapter.inc:729                                                                      [notice]
Undefined variable: annotationData annotationcommand_adapter.inc:729                                                                      [notice]
Undefined variable: annotationData annotationcommand_adapter.inc:729                                                                      [notice]
Undefined variable: annotationData annotationcommand_adapter.inc:729                                                                      [notice]
Beginning to build website.make.yml.                                                                                                 [ok]

Downloading release history from https://updates.drupal.org/release-history/drupal/8.x                                                    [notice]
Executing: wget --version
Executing: wget -q --timeout=30 -O /tmp/download_filejoAhu0 https://updates.drupal.org/release-history/drupal/8.x
Downloading release history from https://updates.drupal.org/release-history/admin_toolbar/8.x                                             [notice]

env COLUMNS=146 /usr/local/bin/drush  --backend=2 --yes --verbose --root= --uri=  pm-download drupal-8.2.1                                [notice]
--destination=/tmp/make_tmp_1476955591_58088dc7cdd0a --package-handler=wget --source=https://updates.drupal.org/release-history
--variant=full --cache --drupal-project-rename=__build__ 2>&1
Undefined index: name annotationcommand_adapter.inc:500                                                                                   [notice]
Loading version_control engine.                                                                                                           [notice]
Loading package_handler engine.                                                                                                           [notice]
Executing: wget --version
Loading release_info engine.                                                                                                              [notice]
Undefined index: name annotationcommand_adapter.inc:500                                                                                   [notice]
Undefined index: name annotationcommand_adapter.inc:500                                                                                   [notice]
Undefined variable: annotationData annotationcommand_adapter.inc:729                                                                      [notice]
Undefined variable: annotationData annotationcommand_adapter.inc:729                                                                      [notice]
Undefined variable: annotationData annotationcommand_adapter.inc:729                                                                      [notice]
Undefined variable: annotationData annotationcommand_adapter.inc:729                                                                      [notice]
Downloading release history from https://updates.drupal.org/release-history/drupal/8.x                                                    [notice]
/home/vagrant/.drush/cache/download/https---updates.drupal.org-release-history-drupal-8.x retrieved from cache.                           [notice]
Downloading project drupal ...                                                                                                            [notice]
/home/vagrant/.drush/cache/download/https---ftp.drupal.org-files-projects-drupal-8.2.1.tar.gz retrieved from cache.                       [notice]
Downloading drupal-8.2.1.tar.gz was successful.                                                                                           [notice]
Md5 checksum of drupal-8.2.1.tar.gz verified.                                                                                             [notice]
Executing: tar  -C /tmp/drush_tmp_1476955592_58088dc801b50 -xzf drupal-8.2.1.tar.gz
Executing: tar -tzf drupal-8.2.1.tar.gz
Executing: svn info /tmp/make_tmp_1476955591_58088dc7cdd0a
Executing: bzr root /tmp/make_tmp_1476955591_58088dc7cdd0a
Project drupal (8.2.1) downloaded to /tmp/make_tmp_1476955591_58088dc7cdd0a/__build__.                                                 [success]
Project drupal contains:                                                                                                               [success]
 - 1 profile: standard
 - 13 themes: minimal, testing_multilingual, drupal_system_listing_compatible_test, testing, testing_config_overrides,
testing_config_import, testing_multilingual_with_english, bartik, classy, stark, stable, seven, twig
 - 70 modules: book, locale, content_moderation, tour, responsive_image, statistics, help, automated_cron, menu_link_content, dblog,
content_translation, ban, hal, field, image, big_pipe, user, outside_in, inline_form_errors, block_content, page_cache, link,
dynamic_page_cache, rdf, migrate_drupal_ui, migrate_drupal, path, contextual, syslog, datetime_range, serialization, rest, color,
language, breakpoint, contact, shortcut, system, entity_reference, basic_auth, search, editor, config, menu_ui, history, views_ui,
telephone, tracker, taxonomy, migrate, options, node, comment, update, forum, text, simpletest, field_ui, block_place, file, filter,
ckeditor, action, aggregator, config_translation, block, datetime, quickedit, toolbar, views</pre>

**Comment by weitzman** [comment]
This was recently fixed in Drush 8.x branch and will be in next release (soon).

**Comment by gitressa** [comment]
Thanks !

**Comment by gwynnebaer** [comment]
I am running 8.1.9 and still see the annotationcommand_adapter.inc warnings. What specific version of Drush 8.x resolves this?

**Comment by weitzman** [comment]
Should be fixed in 8.1.8 and newer. Perhaps you have a Drush thats local to your project and a different one is global on your path? Or your remote server has different drush version. Sometimes running `drush status` is illuminating.
