### ISSUE TITLE
Site Install is broken by drupal 8.6

### ISSUE THREAD

**Issue by pookmish** [drush-ops/drush#3552]
With the latest branch of Drupal 8.6 `drush si` is broken. The changes that broke the command occured as a result of https://www.drupal.org/project/drupal/issues/2911319

using drush 9.2.3 it seems as though the site install command never reads the settings.php file and will ask for database credentials. Even after inputting the credentials it doesn't write those credentials to a settings.php file.

**Comment by cilefen** [comment]
+1 It looks real to me, unless there is something I don't understand about Drush 9. This is not broken in Drush 8 FWIW.

**Comment by alexpott** [comment]
So the problem caused by the changes to \Drupal\Core\Installer\InstallerKernel::createFromRequest()

I'm not sure we should fix this in Drush because it's likely we've caused problems for Drupal Console too. So'll re-open https://www.drupal.org/project/drupal/issues/2969715 but leave this open too.

**Comment by singularo** [comment]
The patch in https://www.drupal.org/project/drupal/issues/2969715#comment-12609678 solved site-install always trying to:

``` // You are about to CREATE the 'drupal' database. Do you want to continue?: yes. ```

Even when a different database was specified in settings.php for 8.6.0-dev with drush 9.3.0.

**Comment by et304383** [comment]
I've updated to the latest drush and the latest drupal core and I still get this same error when running site install from an EC2 instance.

Strange though, if I run locally using the same code base I do NOT get the error about having to delete settings.php

This makes no sense.  How could my PHP environment affect preventing me from installing with an existing settings.php?

**Comment by greg-1-anderson** [comment]
https://www.drupal.org/project/drupal/issues/2969715 has been merged into 8.6.x.  Perhaps this is fixed now.

**Comment by weitzman** [comment]
Pretty sure it is
