### ISSUE TITLE
Drush becomes unusable if a command requires a new module

### ISSUE THREAD

**Issue by deviantintegral** [drush-ops/drush#3574]
If a drush command depends on a service in a module that is not yet enabled, drush can become unusable.

For example, let's say `Custom Module A` adds a Drush command and in it's `drush.services.yml` file uses a service exposed by `Contrib Module B`. In a minor release, `Contrib Module B` alters it's service definition to use a class from a newly added dependency. Note it's not necessarily breaking API contracts; perhaps a new module has some nice implementation of a core-provided interface.

The problem arises when trying to use Drush to run update hooks. As a developer or site builder, I expect I can run `composer update && drush -y updatedb`. However, while discovering all implemented Drush commands, building the container fails because the newly-required class exists in a module that is not yet enabled. As an end user, the only workaround is to use the user interface to run update hooks, or to do two deployments.

There is a way around this [by using a service provider instead of the `drush.services.yml` file](https://github.com/Lullabot/media_mpx/pull/52/files). That lets code do basic checks like `class_exists(...)` before defining a service. However, the services are not as discoverable as a YAML file so the DX for new developers isn't great. As is, I think this is required if you depend on any services or classes outside of the command's module.

There is a related core issue at [Allow updating modules with new service dependencies](https://www.drupal.org/node/2863986).

**Comment by weitzman** [comment]
My first suggestion for fixing this is to change `* @bootstrap full` to `* @bootstrap database`. [See updatedb annotation](https://github.com/drush-ops/drush/blob/44daf5422d3f1cba04bdc36df22a16890c7ba8bd/src/Commands/core/UpdateDBCommands.php#L26). This will prevent Drush from trying to load commandfiles from modules. The rest of the job is just dealing with fallout from that change (if any).

**Comment by weitzman** [comment]
possibly related  https://www.drupal.org/project/drupal/issues/2863986

**Comment by greg-1-anderson** [comment]
It seems to me that `Custom Module A` should only use classes from Drupal Core or from its own code base. I would expect that it would be possible (likely?) that loading classes from a non-enabled `Custom Module B` could cause a crash. I don't know that Drush can validate that the drush.services.yml file is conforming in this way. Would you ever put a dependency between two modules in your `services.yml` file without making the other module a dependency? I wouldn't think so -- and if the other module was a dependency, then it should always be enabled when your module is enabled.

I'd still be in favor of strengthening `drush updatedb` against edge cases like this, even if we need to invent a new bootstrap level (e.g. `full but without Drush extensions`).

**Comment by deviantintegral** [comment]
> Would you ever put a dependency between two modules in your services.yml file without making the other module a dependency? I wouldn't think so -- and if the other module was a dependency, then it should always be enabled when your module is enabled.

Nope, that's exactly the problem. Even though the module has properly added the dependency to the info file, if in the same deployment it adds a service or Drush command that uses that dependency, you can't successfully complete `updatedb`. The service container is built too early, and the container build fails.

**Comment by weitzman** [comment]
So is the issue I pointed to above unrelated?

**Comment by deviantintegral** [comment]
I think it's the same class of bug, but my understanding was the Drush had it's own code for drush services, and that fixing that core issue wouldn't fix drush commands.

**Comment by jcisio** [comment]
I run into this problem. This issue has been fixed in Drupal https://www.drupal.org/node/3067480 but this fix should be ported to drush manually.

**Comment by pfrenssen** [comment]
I had the same problem today but did not find this issue and had opened a duplicate. Here is a copy of the information I posted in #4216, it contains some additional information that is not yet mentioned here:



**Describe the bug**
I am trying to deploy a new feature that introduces a new custom module in my project. In this module there is a new service which will be used by some of the existing services in the existing modules.

So in the production database this new module with the new service dependency is not yet enabled. The new module will be enabled when I run `drush config:import`, but unfortunately when I run this command I get the following error:

```
    [drush] Executing command: ./vendor/bin/drush --root="./web" --verbose --yes config:import

In CheckExceptionOnInvalidReferenceBehaviorPass.php line 31:

  [Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException]
  The service "asset_release.fulfillment_guard" has a dependency on a non-existent service "workflow_state_permission.workflow_state_permission".
```

This is because the dependency container is built using the standard `DrupalKernel` which detects if a non-existing dependency is used and refuses to build. We should instead use the `UpdateKernel` which will skip all unmet dependencies automatically (ref. `UpdateCompilerPass::process()`). This has been introduced recently in Drupal 8.7.x, ref [Change record #3067480: The UpdateKernel removes services with unmet dependencies from the container](https://www.drupal.org/node/3067480).

I naively tried to add the annotation `@kernel update` to the `ConfigImportCommands::import()` command but this doesn't work. The `config:import` command is itself a service, so it is only discovered _after_ Drupal is already fully bootstrapped in `\Drush\Application::bootstrapAndFind()`. Unfortunately this will bootstrap the default `DrupalKernel` and will crash before it even has the chance to discover the command.

**To Reproduce**
* Add a new module that introduces a new service dependency.
* Run `drush config:import`

**Expected behavior**
* The config is imported.

**Actual behavior**
* `Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException: The service "existing_module.existing_service" has a dependency on a non-existent service "new_module.new_service".`

**Workaround**
* Not tested but probably it is possible to enable the new module in a `hook_update_n()` hook before running `drush config:import`.

### System Configuration
| Q               | A
| --------------- | ---
| Drush version?  | 9.x
| Drupal version? | 8.7.x\|8.8.x
| PHP version     | 5.x\|7.x
| OS?             | Mac\|Linux\|Windows\|Unix


I think this can be fixed in a non-invasive way by providing a wrapper command (`Drush\Commands\config\ConfigImportCommands`) that pretends to not be a service so it can be discovered without needing a full bootstrap. We can annotate this new wrapper command with `@bootstrap full` and `@kernel update` so Drupal will be fully bootstrapped using the `UpdateKernel` when the command is invoked.

Then we can let the wrapper call into the "real" service based command (`Drush\Drupal\Commands\config\ConfigImportCommands`) by accessing it statically using `\Drupal::service('config.import.commands')->import()`.

**Comment by pfrenssen** [comment]
I'm tagging this with `area-config` since the problems reported in the OP with `updatedb` are already fixed in the meantime. The problem currently still happens in `config:import`.

**Comment by pfrenssen** [comment]
I have posted a proposed PR at #4217 but one of the tests is failing, it needs investigation.
